<a href="https://colab.research.google.com/github/Retr0Sys/Clasificaci-n-PLN-de-Clasificaci-n-de-opiniones-IA/blob/main/Clasificaci%C3%B3n_PLN_de_Clasificaci%C3%B3n_de_opiniones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Importamos el .csv**

In [32]:
import pandas as pd
df = pd.read_csv("dataset_train_95.csv")

## **Vemos parte del contenido con un head**

In [33]:
df.head(5)

,id,autor,declaracion,etiqueta,palabras_clave,tweet,respuesta_mayoria_5_etiquetas,respuesta_mayoria_3_etiquetas
0,116196,Ciara O'Rourke,CDC just cancelled Halloween for kids.,0,"CDC, cancelled, Halloween",If the CDC wants people to not crowd and party...,Agree,Agree
1,118599,Ciara O'Rourke,Coroner saying George Floyd died of drug overd...,0,"George Floyd, died, drug overdose",@GlennLoury George Floyd died of a drug overdo...,NO MAJORITY,Agree
2,133975,Tom Kertscher,Says Nancy Pelosi made millions in coronavirus...,0,"pelosi, made millions, insider trading",@hrkbenowen Pelosis husband who made via insid...,Agree,Agree
3,92314,Caryn Shinske,"New Jersey has ""the highest property taxes in ...",1,"New Jersey, highest property taxes",@POTUS I'll believe it when I see it...I work ...,Mostly Agree,Agree
4,72507,Louis Jacobson,"""Nearly 6 out of 10 believe that money and wea...",1,"money, more evenly distributed",@1913endedUSA @cindiph94423981 @dbartgallery @...,Agree,Agree

## **Comprobamos si hay datos vacios**

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81591 entries, 0 to 81590
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             81591 non-null  int64
 1   autor                          81591 non-null  object
 2   declaracion                    81591 non-null  object
 3   etiqueta                       81591 non-null  int64
 4   palabras_clave                 81591 non-null  object
 5   tweet                          81591 non-null  object
 6   respuesta_mayoria_5_etiquetas  81591 non-null  object
 7   respuesta_mayoria_3_etiquetas  81591 non-null  object
dtypes: int64(2), object(6)
memory usage: 5.0+ MB

## **Vemos la cantidad de datos vacíos**

In [35]:
df.isnull().sum()

id                               0
autor                            0
declaracion                      0
etiqueta                         0
palabras_clave                   0
tweet                            0
respuesta_mayoria_5_etiquetas    0
respuesta_mayoria_3_etiquetas    0
dtype: int64

## **Eliminamos duplicados**

In [36]:
print("Cantidad de filas antes de eliminar duplicado", df.shape)
df.drop_duplicates(inplace=True)
print("Cantidad de filas después de eliminar duplicado", df.shape)

Cantidad de filas antes de eliminar duplicado (81591, 8)
Cantidad de filas después de eliminar duplicado (81591, 8)

## **Creamos el modelo**

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['declaracion'], df['etiqueta'], test_size=0.10)

from sklearn.model_selection import train_test_split

X2_train, X2_test, y2_train, y2_test = train_test_split(df['tweet'], df['etiqueta'], test_size=0.10)

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizador = CountVectorizer()
X_train_vec = vectorizador.fit_transform(X_train)
X_test_vec = vectorizador.transform(X_test)

from sklearn.feature_extraction.text import CountVectorizer

vectorizador = CountVectorizer()
X2_train_vec = vectorizador.fit_transform(X2_train)
X2_test_vec = vectorizador.transform(X2_test)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelo = LogisticRegression()
modelo.fit(X_train_vec, y_train)

predit = modelo.predict(X_test_vec)

accuracy = accuracy_score(y_test, predit)
print("Porcentaje de acierto primer modelo:", accuracy * 100)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

modelo = LogisticRegression()
modelo.fit(X2_train_vec, y2_train)

predit2 = modelo.predict(X2_test_vec)

accuracy2 = accuracy_score(y2_test, predit2)
print("Porcentaje de acierto segundo modelo:", accuracy2 * 100)

Porcentaje de acierto primer modelo: 99.93872549019608
Porcentaje de acierto segundo modelo: 98.00245098039215

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## **Leemos el .csv de prueba**

In [40]:
test_data = pd.read_csv('dataset_test_5_sin_etiqueta.csv')
test_data2 = pd.read_csv('dataset_test_5_sin_etiqueta.csv')


test_data.head()

,id,autor,declaracion,palabras_clave,tweet,respuesta_mayoria_5_etiquetas,respuesta_mayoria_3_etiquetas
0,100845,Samantha Putterman,Nancy Pelosi is no longer the Speaker of the H...,"Nancy Pelosi, no longer, Speaker",@Yamiche That really doesn't bear repeating. A...,Mostly Agree,Agree
1,8962,Madlin Mekelburg,Says Texas either is near the bottom or at the...,"Texas, testing per capita",@ElisaCardnell Testing per capita in Texas 6.5...,Agree,Agree
2,49832,Bill McCarthy,The mRNA COVID-19 vaccines are really gene the...,"vaccine,gene therapy,mRNA",I think we should stop calling the mRNA stuff ...,NO MAJORITY,Agree
3,34401,Sarah Hauer,"Since 1978, college ""tuition nationwide has go...","college tuition, inflation rate",@irataavis @AMERICAN__TGM I paid for my own co...,Mostly Agree,Agree
4,86818,Tom Kertscher,Donald J. Trumps signature is on the new stimu...,"trump,signature,stimulus checks",@JeffSco70032223 @FigZayas @zrs9504 @maziehiro...,Agree,Agree

## **Creamos el archivo de salida**

In [41]:
X_test_vec = vectorizador.transform(test_data['declaracion'])

predict = modelo.predict(X_test_vec)

output = pd.DataFrame({'id': test_data['id'], 'etiqueta': predict})
output.to_csv('submission.csv', index=False)

print("Archivo creado con éxito")


X2_test_vec = vectorizador.transform(test_data2['declaracion'])

predict2 = modelo.predict(X2_test_vec)

output = pd.DataFrame({'id': test_data['id'], 'etiqueta': predict})
output.to_csv('submission2.csv', index=False)

print("Archivo creado con éxito")

Archivo creado con éxito
Archivo creado con éxito